apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: f3d3406ab82eaf6118f616c1ace1537630e688a9
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: e1c8f62c8aa4ccd5f572a4143cda3639c050f351
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
