apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 16047833a36a20641772d1165b73fd89b783a407
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 87aa925e7c67ab28c281bbee4d48d750c87ae8de
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
