apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 582cdb676b77303fdafd4a9f036767be1c287469
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 828cc336cbcb946937032ec2420df33482f69a88
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
