apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: airdevops/medkick-api
  newName: airdevops/medkick-api
  newTag: 801bbd0875a37f060696218c7094bd4cbc953275
- name: airdevops/medkick-frontend
  newName: airdevops/medkick-frontend
  newTag: 3a9869532fbc8f9e2bd12a8db785303f6ce73489
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
