apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: medkickdevops/medkick-api
  newName: medkickdevops/medkick-api
  newTag: 0076de93b7991eebea79c5da77877f30c0b581ab
- name: medkickdevops/medkick-frontend
  newName: medkickdevops/medkick-frontend
  newTag: 3a9869532fbc8f9e2bd12a8db785303f6ce73489
- name: medkickdevops/rpmsoftware-api
  newName: medkickdevops/rpmsoftware-api
  newTag: 4fd693b59ab3a0980abec9e8e571a5f2310f6d6a
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
