apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: medkickdevops/rpmsoftware-api
  newName: medkickdevops/rpmsoftware-api
  newTag: 0076de93b7991eebea79c5da77877f30c0b581ab
- name: medkickdevops/rpmsoftware-frontend
  newName: medkickdevops/rpmsoftware-frontend
  newTag: 3a9869532fbc8f9e2bd12a8db785303f6ce73489
- name: medkickdevops/rpmsoftware-api
  newName: medkickdevops/rpmsoftware-api
  newTag: 52bd64ea1ffc2c47d85af8ec1f8b589afc88d4f9
- name: medkickdevops/rpmsoftware-frontend
  newName: medkickdevops/rpmsoftware-frontend
  newTag: 7b38a20f1de8be6423529b666df362188c0d5d52
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
