apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 9b494a79b9efd6b59115a278870a0a1dcdf6df24
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: da4f2b9ecd6ca23fc7a8cd259da4350405a2833b
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
