apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: medkickdevops/rpmsoftware-api
  newName: medkickdevops/rpmsoftware-api
  newTag: 98f2126730d1e6b3df1dc8b974a41533b095ff4f
- name: medkickdevops/rpmsoftware-frontend
  newName: medkickdevops/rpmsoftware-frontend
  newTag: 3a9869532fbc8f9e2bd12a8db785303f6ce73489
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
