apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 1fa8c69580fa747c74ecaaa8a1f75340a0bfa6f1
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: be8b520221afbb38b01988be5178d5b430cc2b3d
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
