apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 0f6aad5dd537977ac0bb13fa9bfefedc60a355bc
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 46a1f2a496e4a36ad9cf049a81f9658bf412fa28
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
