apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 2f5e8a4ea7865caf6a88347a0d111ef77e340f63
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: ed13e3383a6959a8b3a36a792121fa40ccfe87aa
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
