apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: airdevops/medkick-api
  newName: airdevops/medkick-api
  newTag: f6393b820e500bde27c857666aef2f34a01baa21
- name: airdevops/medkick-frontend
  newName: airdevops/medkick-frontend
  newTag: 3a9869532fbc8f9e2bd12a8db785303f6ce73489
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
