apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: ff998ee206ff439523ab50a34d9fac29a6f09d0d
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 828cc336cbcb946937032ec2420df33482f69a88
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
