apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-medkick-rpm-com-tls
spec:
  dnsNames:
    - api-prod.medkick-rpm.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-medkick-rpm-com-tls
