apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-medkick-air-business-tls
spec:
  dnsNames:
    - www.medkick.air.business
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-medkick-air-business-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: development-medkick-rpm-com-tls
spec:
  dnsNames:
    - development.medkick-rpm.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: development-medkick-rpm-com-tls
