apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-medkick-rpm-com-tls
spec:
  dnsNames:
    - www.medkick-rpm.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-medkick-rpm-com-tls
