apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: airdevops/medkick-api
  newName: airdevops/medkick-api
  newTag: 7a0ffb9745748745753e94d6577a2165a9815715
- name: airdevops/medkick-frontend
  newName: airdevops/medkick-frontend
  newTag: 034d83a1e902466ca86e8955365e8b52a9590c07
