apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 2d6e65fc0c6454ac27e752c7ef0d8e855fdefd67
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 8c297d0ed209af9f186b67b7e58cc8aa4a65a1c5
