apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: medkickdevops/rpmsoftware-frontend
  newName: medkickdevops/rpmsoftware-frontend
  newTag: 034d83a1e902466ca86e8955365e8b52a9590c07
- name: medkickdevops/rpmsoftware-api
  newName: medkickdevops/rpmsoftware-api
  newTag: 6a2c2a013d1eb53b407105d1ba46d8850cd0f4d4
- name: medkickdevops/rpmsoftware-frontend
  newName: medkickdevops/rpmsoftware-frontend
  newTag: 62dd7374a61838793494420b5172898cf4512226
