apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: airdevops/medkick-api
  newName: airdevops/medkick-api
  newTag: ba2b46f1a738e80d0eea30a14f784bc6a98748a4
- name: airdevops/medkick-frontend
  newName: airdevops/medkick-frontend
  newTag: 034d83a1e902466ca86e8955365e8b52a9590c07
