apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 15508bbf1a93d5b20555b3c2d74b029539c8c6b6
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 554f3a0b297874fdb073def59c14e7699897049a
