apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 249ae75c6f706b200e1781440cedd73cfd05bdc4
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 4e7e2fb972855ac5e3573b98d7b98248024e1335
