apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: cbee6c6acefceab0affff9c563128627b85a6182
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 4dfa8a3fcdce4738c62544450cc16b9213138c9a
