apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: be29065754c7a8a5eccafe929893446b19d7e574
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 0678c99e114b80ed00ccb53247bf9a3738c96ba0
