apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: f6306ee6e46dca85a355ab719106b2d49f15a86a
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 59b4a07b636edae292ad27811f1100deab3585bc
