apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 7ece95410ffdf6a282497bbd565433510cb963a8
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 827537ccdc4db51eb9f62eb96dd5b8d92b0c255c
