apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: f2c5073494ab96ae4ac3c2946160f0d028508e0d
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 59a03a437a79e95002dc0e2b356fa6b9d8721343
