apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: medkickdevops/medkick-api
  newName: medkickdevops/medkick-api
  newTag: 0076de93b7991eebea79c5da77877f30c0b581ab
- name: medkickdevops/medkick-frontend
  newName: medkickdevops/medkick-frontend
  newTag: 034d83a1e902466ca86e8955365e8b52a9590c07
- name: medkickdevops/medkick-frontend
  newName: medkickdevops/medkick-frontend
  newTag: e7985f615840f3c9aecfa4a688b98da85d6e4e98
