apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: medkickdevops/rpmsoftware-api
  newName: medkickdevops/rpmsoftware-api
  newTag: 6a2c2a013d1eb53b407105d1ba46d8850cd0f4d4
- name: medkickdevops/rpmsoftware-frontend
  newName: medkickdevops/rpmsoftware-frontend
  newTag: 4d921fc1dc79434fe9ad4739aa1ad0c3d43a3e26
