apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: ff04d0ff3b0d53981f5c50c587be449160aff9ca
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 46b690971a282f2ea8a79edd39193958a33fb17d
