apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 600a0f79f7dc6707ac76245c700d45c5f1c6cf1a
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 3aa62859940a66f001c1f72c14d2f00441f515bf
