apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 90efd6720bca9698fe82f03183e2e62f3a6d75d2
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 6517fd4376e71df58cbf1d0e9e046ab7899d429c
