apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: raajpatel229/medkick-api
  newName: raajpatel229/medkick-api
  newTag: 64e0d2038d548f8b6ef688b949bce266dbba84a7
- name: raajpatel229/medkick-frontend
  newName: raajpatel229/medkick-frontend
  newTag: 6517fd4376e71df58cbf1d0e9e046ab7899d429c
